# Simple Netlify configuration for Learn Options Trading App
[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION = "10"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

# Don't cache HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Production context
[context.production]
  command = "npm ci && npm run build"
  environment = { NODE_ENV = "production" }

# Deploy previews
[context.deploy-preview]
  command = "npm install && npm run build"
  environment = { NODE_ENV = "development" }