# Netlify configuration for Learn Options Trading App
[build]
  # Simple, reliable build command with environment validation
  command = "npm install && npm run build"
  publish = "dist"

# Custom domain configuration
[[redirects]]
  from = "https://www.learnoptionstrading.academy/*"
  to = "https://learnoptionstrading.academy/:splat"
  status = 301
  force = true

[build.environment]
  # Use Node 20 for best compatibility with Vite 5+
  NODE_VERSION = "20"
  # Ensure environment variables are properly loaded
  NPM_FLAGS = "--prefer-offline --no-audit"
  # Security: Disable smart detection for false positives (no Google API keys used)
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

# Context-specific builds
[context.production]
  command = "npm ci && npm run build"

[context.deploy-preview]
  command = "npm ci && npm run build"

[context.branch-deploy]
  command = "npm ci && npm run build"
# Build optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Cache node_modules but allow fresh installs when needed
[build.cache]
  paths = ["node_modules"]

# SPA routing - redirect all paths to index.html except static files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Host = ["learnoptionstrading.academy", "www.learnoptionstrading.academy"]}
  force = false

# Security and performance headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

    # Default cache
    Cache-Control = "public, max-age=0, must-revalidate"

# Don't cache HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Don't cache service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# CSS files - long cache with immutable
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# JS files - moderate cache with revalidation
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800, stale-while-revalidate=86400"
    Content-Type = "application/javascript; charset=utf-8"

# JS module files in assets directory
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800, stale-while-revalidate=86400"
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

# Static assets (images, fonts) - long cache
[[headers]]
  for = "/assets/*.{png,jpg,jpeg,gif,svg,webp,woff,woff2,ttf,eot}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"