# Netlify configuration for Learn Options Trading App
[build]
  # Linux-compatible build command
  command = "npm ci && npm run build"
  
  # Output directory
  publish = "dist"
  
  # Functions directory (if you add serverless functions later)
  functions = "netlify/functions"

[build.environment]
  # Node version (use LTS)
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  
  # Disable telemetry for faster builds
  CI = "true"

# Cache settings - cache node_modules but not Vite cache
[build.cache]
  paths = ["node_modules"]

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects (for future backend integration)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control for static assets
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    # Don't cache HTML files
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    # Don't cache service worker
    Cache-Control = "public, max-age=0, must-revalidate"

# Environment-specific builds
[context.production]
  command = "npm ci && npm run build"
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  command = "npm install && npm run build"
  environment = { NODE_ENV = "development" }

[context.branch-deploy]
  command = "rm -rf node_modules/.vite && npm install && npm run build"

# Functions settings (for future serverless functions)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Dev server settings
[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"
  autoLaunch = false