# Simple Netlify configuration for Learn Options Trading App
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "vite"
  targetPort = 5173
  port = 8888
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# AGGRESSIVE cache busting for JS files
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Expires = "0"
    Pragma = "no-cache"

# Force HTML refresh
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Expires = "0"
    Pragma = "no-cache"

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Production context
[context.production]
  command = "npm install && npm run build"
  environment = { NODE_ENV = "production" }

# Deploy previews
[context.deploy-preview]
  command = "npm install && npm run build"
  environment = { NODE_ENV = "development" }