# Netlify configuration for Learn Options Trading App
[build]
  # Simple, reliable build command
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  # Use Node 20 for best compatibility with Vite 5+
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  CI = "true"
  # Disable npm audit for faster builds
  NPM_CONFIG_AUDIT = "false"
# Build optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Cache node_modules but allow fresh installs when needed
[build.cache]
  paths = ["node_modules"]

# SPA routing - redirect all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = [], Country = []}

# Future API routes (if you add serverless functions)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Security and performance headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance - cache static assets
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Don't cache service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# CSS files - long cache with immutable
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# JS files - long cache with immutable
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Production context
[context.production]
  command = "npm ci && npm run build"
  environment = { NODE_ENV = "production" }

# Deploy previews
[context.deploy-preview]
  command = "CI= npm install && npm run build"
  environment = { NODE_ENV = "development" }

# Branch deploys
[context.branch-deploy]
  command = "CI= npm install && npm run build"
  environment = { NODE_ENV = "development" }

# Functions configuration (for future use)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js", "date-fns"]

# Form handling (if you add contact forms later)
[form]
  settings = { external = false }