import { Achievement, Challenge } from '../types/gamification';

// Sample Achievements
export const SAMPLE_ACHIEVEMENTS: Achievement[] = [
  // First Steps (10 achievements)
  {
    id: 'first_trade',
    name: 'First Trade',
    description: 'Place your very first trade',
    category: 'first_steps',
    rarity: 'common',
    icon: '🎯',
    xpReward: 100,
    coinReward: 10,
    requirement: 'Place 1 trade',
    requirement_value: 1,
  },
  {
    id: 'first_option',
    name: 'Options Explorer',
    description: 'Trade your first option contract',
    category: 'first_steps',
    rarity: 'common',
    icon: '📊',
    xpReward: 150,
    coinReward: 15,
    requirement: 'Trade 1 option',
    requirement_value: 1,
  },
  {
    id: 'first_profit',
    name: 'First Profit',
    description: 'Close a trade with profit',
    category: 'first_steps',
    rarity: 'uncommon',
    icon: '💰',
    xpReward: 200,
    coinReward: 20,
    requirement: 'Close 1 profitable trade',
    requirement_value: 1,
  },
  {
    id: 'ten_trades',
    name: 'Active Trader',
    description: 'Execute 10 trades',
    category: 'first_steps',
    rarity: 'uncommon',
    icon: '📈',
    xpReward: 250,
    coinReward: 25,
    requirement: 'Execute 10 trades',
    requirement_value: 10,
  },
  {
    id: 'watchlist_created',
    name: 'Watchlist Starter',
    description: 'Add 5 stocks to your watchlist',
    category: 'first_steps',
    rarity: 'common',
    icon: '👀',
    xpReward: 100,
    coinReward: 10,
    requirement: 'Add 5 stocks to watchlist',
    requirement_value: 5,
  },

  // Strategy Mastery (15 achievements)
  {
    id: 'first_spread',
    name: 'Spread Trader',
    description: 'Execute your first spread trade',
    category: 'strategy_mastery',
    rarity: 'rare',
    icon: '🎨',
    xpReward: 300,
    coinReward: 30,
    requirement: 'Execute 1 spread',
    requirement_value: 1,
  },
  {
    id: 'iron_condor',
    name: 'Iron Condor Master',
    description: 'Successfully execute an iron condor',
    category: 'strategy_mastery',
    rarity: 'rare',
    icon: '🦅',
    xpReward: 500,
    coinReward: 50,
    requirement: 'Execute 1 iron condor',
    requirement_value: 1,
  },
  {
    id: 'butterfly_spread',
    name: 'Butterfly Collector',
    description: 'Execute a butterfly spread',
    category: 'strategy_mastery',
    rarity: 'epic',
    icon: '🦋',
    xpReward: 750,
    coinReward: 75,
    requirement: 'Execute 1 butterfly spread',
    requirement_value: 1,
  },
  {
    id: 'straddle_master',
    name: 'Straddle Specialist',
    description: 'Execute 5 straddle strategies',
    category: 'strategy_mastery',
    rarity: 'rare',
    icon: '⚡',
    xpReward: 600,
    coinReward: 60,
    requirement: 'Execute 5 straddles',
    requirement_value: 5,
  },
  {
    id: 'strategy_variety',
    name: 'Strategic Diversity',
    description: 'Execute 10 different strategy types',
    category: 'strategy_mastery',
    rarity: 'legendary',
    icon: '🌟',
    xpReward: 1500,
    coinReward: 150,
    requirement: 'Execute 10 different strategies',
    requirement_value: 10,
  },

  // Greeks Guru (10 achievements)
  {
    id: 'delta_aware',
    name: 'Delta Conscious',
    description: 'Use delta in a trading decision',
    category: 'greeks_guru',
    rarity: 'uncommon',
    icon: 'Δ',
    xpReward: 200,
    coinReward: 20,
    requirement: 'Use delta once',
    requirement_value: 1,
  },
  {
    id: 'gamma_scalper',
    name: 'Gamma Scalper',
    description: 'Execute 5 gamma scalp trades',
    category: 'greeks_guru',
    rarity: 'rare',
    icon: 'Γ',
    xpReward: 500,
    coinReward: 50,
    requirement: 'Execute 5 gamma scalps',
    requirement_value: 5,
  },
  {
    id: 'theta_decay',
    name: 'Theta Harvester',
    description: 'Profit from theta decay 10 times',
    category: 'greeks_guru',
    rarity: 'epic',
    icon: 'Θ',
    xpReward: 800,
    coinReward: 80,
    requirement: 'Profit from theta 10 times',
    requirement_value: 10,
  },
  {
    id: 'vega_trader',
    name: 'Volatility Expert',
    description: 'Successfully trade vega 15 times',
    category: 'greeks_guru',
    rarity: 'epic',
    icon: 'ν',
    xpReward: 1000,
    coinReward: 100,
    requirement: 'Trade vega 15 times',
    requirement_value: 15,
  },
  {
    id: 'greeks_master',
    name: 'Greeks Grandmaster',
    description: 'Master all Greeks in trading',
    category: 'greeks_guru',
    rarity: 'legendary',
    icon: '🏛️',
    xpReward: 2000,
    coinReward: 200,
    requirement: 'Use all Greeks effectively',
    requirement_value: 1,
    hint: 'Master delta, gamma, theta, vega, and rho',
  },

  // Risk Management (12 achievements)
  {
    id: 'stop_loss_hero',
    name: 'Stop Loss Discipline',
    description: 'Use stop loss in 10 trades',
    category: 'risk_management',
    rarity: 'uncommon',
    icon: '🛡️',
    xpReward: 300,
    coinReward: 30,
    requirement: 'Use stop loss 10 times',
    requirement_value: 10,
  },
  {
    id: 'position_sizer',
    name: 'Position Sizing Pro',
    description: 'Use proper position sizing in 20 trades',
    category: 'risk_management',
    rarity: 'rare',
    icon: '⚖️',
    xpReward: 500,
    coinReward: 50,
    requirement: 'Proper sizing 20 times',
    requirement_value: 20,
  },
  {
    id: 'hedge_master',
    name: 'Hedging Expert',
    description: 'Successfully hedge 15 positions',
    category: 'risk_management',
    rarity: 'epic',
    icon: '🔒',
    xpReward: 1000,
    coinReward: 100,
    requirement: 'Hedge 15 positions',
    requirement_value: 15,
  },

  // Profit Milestones (10 achievements)
  {
    id: 'profit_1k',
    name: 'First Thousand',
    description: 'Reach $1,000 in total profits',
    category: 'profit_milestones',
    rarity: 'uncommon',
    icon: '💵',
    xpReward: 500,
    coinReward: 50,
    requirement: 'Earn $1,000',
    requirement_value: 1000,
  },
  {
    id: 'profit_5k',
    name: 'Five Grand Club',
    description: 'Reach $5,000 in total profits',
    category: 'profit_milestones',
    rarity: 'rare',
    icon: '💸',
    xpReward: 1000,
    coinReward: 100,
    requirement: 'Earn $5,000',
    requirement_value: 5000,
  },
  {
    id: 'profit_10k',
    name: 'Ten K Trader',
    description: 'Reach $10,000 in total profits',
    category: 'profit_milestones',
    rarity: 'epic',
    icon: '💎',
    xpReward: 2000,
    coinReward: 200,
    requirement: 'Earn $10,000',
    requirement_value: 10000,
  },
  {
    id: 'win_rate_70',
    name: 'Consistent Winner',
    description: 'Achieve 70% win rate over 50 trades',
    category: 'profit_milestones',
    rarity: 'legendary',
    icon: '🏆',
    xpReward: 3000,
    coinReward: 300,
    requirement: '70% win rate in 50 trades',
    requirement_value: 70,
  },

  // Consistency & Discipline (15 achievements)
  {
    id: 'streak_7',
    name: 'Week Warrior',
    description: 'Maintain a 7-day trading streak',
    category: 'consistency',
    rarity: 'uncommon',
    icon: '🔥',
    xpReward: 300,
    coinReward: 30,
    requirement: '7-day streak',
    requirement_value: 7,
  },
  {
    id: 'streak_30',
    name: 'Monthly Champion',
    description: 'Maintain a 30-day trading streak',
    category: 'consistency',
    rarity: 'epic',
    icon: '⚡',
    xpReward: 1500,
    coinReward: 150,
    requirement: '30-day streak',
    requirement_value: 30,
  },
  {
    id: 'streak_100',
    name: 'Century Streaker',
    description: 'Maintain a 100-day trading streak',
    category: 'consistency',
    rarity: 'legendary',
    icon: '👑',
    xpReward: 5000,
    coinReward: 500,
    requirement: '100-day streak',
    requirement_value: 100,
  },

  // Community & Social (10 achievements)
  {
    id: 'first_share',
    name: 'Strategy Sharer',
    description: 'Share your first strategy',
    category: 'community',
    rarity: 'common',
    icon: '🤝',
    xpReward: 150,
    coinReward: 15,
    requirement: 'Share 1 strategy',
    requirement_value: 1,
  },
  {
    id: 'helpful_trader',
    name: 'Community Helper',
    description: 'Help 10 other traders',
    category: 'community',
    rarity: 'rare',
    icon: '💙',
    xpReward: 600,
    coinReward: 60,
    requirement: 'Help 10 traders',
    requirement_value: 10,
  },

  // Learning & Education (18 achievements)
  {
    id: 'first_lesson',
    name: 'Eager Learner',
    description: 'Complete your first lesson',
    category: 'learning',
    rarity: 'common',
    icon: '📚',
    xpReward: 100,
    coinReward: 10,
    requirement: 'Complete 1 lesson',
    requirement_value: 1,
  },
  {
    id: 'course_complete',
    name: 'Course Graduate',
    description: 'Complete an entire course',
    category: 'learning',
    rarity: 'rare',
    icon: '🎓',
    xpReward: 800,
    coinReward: 80,
    requirement: 'Complete 1 course',
    requirement_value: 1,
  },
  {
    id: 'quiz_master',
    name: 'Quiz Champion',
    description: 'Score 100% on 5 quizzes',
    category: 'learning',
    rarity: 'epic',
    icon: '🏅',
    xpReward: 1200,
    coinReward: 120,
    requirement: 'Perfect score on 5 quizzes',
    requirement_value: 5,
  },
];

// Sample Daily Challenges
export function generateDailyChallenges(): Challenge[] {
  const today = new Date();
  const expiresAt = new Date(today);
  expiresAt.setHours(23, 59, 59, 999);

  return [
    {
      id: 'daily_trades_3',
      title: 'Place 3 Trades',
      description: 'Execute at least 3 trades today',
      type: 'daily',
      icon: '🎯',
      xpReward: 100,
      coinReward: 10,
      requirement: 3,
      category: 'trading',
      expiresAt,
    },
    {
      id: 'daily_profit',
      title: 'Close a Profitable Trade',
      description: 'Close at least one trade with profit today',
      type: 'daily',
      icon: '💰',
      xpReward: 150,
      coinReward: 15,
      requirement: 1,
      category: 'profit',
      expiresAt,
    },
    {
      id: 'daily_greeks',
      title: 'Use Greeks in a Decision',
      description: 'Consider Greeks when placing a trade today',
      type: 'daily',
      icon: 'Δ',
      xpReward: 75,
      coinReward: 8,
      requirement: 1,
      category: 'analysis',
      expiresAt,
    },
  ];
}

// Sample Weekly Challenges
export function generateWeeklyChallenges(): Challenge[] {
  const today = new Date();
  const expiresAt = new Date(today);
  expiresAt.setDate(expiresAt.getDate() + (7 - expiresAt.getDay()));
  expiresAt.setHours(23, 59, 59, 999);

  return [
    {
      id: 'weekly_streak',
      title: 'Maintain a 7-Day Streak',
      description: 'Trade every day this week',
      type: 'weekly',
      icon: '🔥',
      xpReward: 500,
      coinReward: 50,
      requirement: 7,
      category: 'consistency',
      expiresAt,
    },
    {
      id: 'weekly_lessons',
      title: 'Complete 5 Strategy Lessons',
      description: 'Learn 5 new strategies this week',
      type: 'weekly',
      icon: '📚',
      xpReward: 300,
      coinReward: 30,
      requirement: 5,
      category: 'learning',
      expiresAt,
    },
    {
      id: 'weekly_strategies',
      title: 'Try 3 Different Strategies',
      description: 'Execute at least 3 different strategy types',
      type: 'weekly',
      icon: '🎨',
      xpReward: 400,
      coinReward: 40,
      requirement: 3,
      category: 'strategy',
      expiresAt,
    },
  ];
}

// Sample Monthly Challenges
export function generateMonthlyChallenges(): Challenge[] {
  const today = new Date();
  const expiresAt = new Date(today.getFullYear(), today.getMonth() + 1, 0, 23, 59, 59, 999);

  return [
    {
      id: 'monthly_profit',
      title: 'Achieve 20% Portfolio Growth',
      description: 'Grow your portfolio by 20% this month',
      type: 'monthly',
      icon: '📈',
      xpReward: 2000,
      coinReward: 200,
      requirement: 20,
      category: 'profit',
      expiresAt,
    },
    {
      id: 'monthly_trades',
      title: 'Execute 100 Trades',
      description: 'Place 100 trades this month',
      type: 'monthly',
      icon: '💼',
      xpReward: 1500,
      coinReward: 150,
      requirement: 100,
      category: 'trading',
      expiresAt,
    },
    {
      id: 'monthly_winrate',
      title: 'Maintain 65% Win Rate',
      description: 'Keep a win rate above 65% for the month',
      type: 'monthly',
      icon: '🏆',
      xpReward: 3000,
      coinReward: 300,
      requirement: 65,
      category: 'consistency',
      expiresAt,
    },
  ];
}
